Move 3.6 Client Test to Separate Class
Depending on test execution order, can cause

IllegalArgumentException: object is not an instance of declaring class

since we now store the `Method` for execution in a static variable.