AMQP-828: No Exception on normal close
JIRA: https://jira.spring.io/browse/AMQP-828
JIRA: https://jira.spring.io/browse/AMQP-829

When a channel is closed normally (e.g. due to a timeout), the shutdown listener
completed the future with the `ShutdownSignalException`.

2018-08-28 05:09:18,261 ERROR org.springframework.amqp.rabbit.core.RabbitTemplate [Test worker] : Consumer failed to receive message: TemplateConsumer [channel=Cached Rabbit Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://guest@127.0.0.1:5672/,1), conn: Proxy@39754e71 Shared Rabbit Connection: SimpleConnection@1a81c806 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 59780], consumerTag=null]
com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)

This preempts the `ConsumeOkNotReceivedException` in some tests, since the future is already complete.

**cherry-pick to 1.7.x** Will submit a separate PR for master since there's another future there.