Restore deprecated `MLC` on impls as upper bound
Moving container implementations to a new interface
is a breaking change from the exising API relying
on the already deprecated interface yet.
We just cannot just into a new interface immediately
since existing projects might not use a new version of
using API yet.

One of the downstream project build failures is like:
```
 /home/runner/work/spring-integration/spring-integration/spring-integration-amqp/src/main/java/org/springframework/integration/amqp/dsl/AmqpInboundChannelAdapterDMLCSpec.java:33: error: type argument DirectMessageListenerContainer is not within bounds of type-variable C
		extends AmqpInboundChannelAdapterSpec<AmqpInboundChannelAdapterDMLCSpec, DirectMessageListenerContainer> {
		                                                                         ^
  where C is a type-variable:
    C extends MessageListenerContainer declared in class AmqpInboundChannelAdapterSpec
```

* Bring back deprecated `org.springframework.amqp.rabbit.listener.MessageListenerContainer`
onto exising implementations to avoid a breaking change.